export const words = [
  "The Orb",
  "The Railroad",
  "Wormwood",
  "Brimstone",
  "Spades",
  "The Whale",
  "Stewpot",
  "Bonaparte",
  "Augustín de Vedia",
  "Nº Nine",
  "Rasputin",
  "Black Phillip",
  "Meat Blanket",
  "The Oceans",
  "Silvery Spider",
  "Dark Pyramid",
  "Labyrinth",
  "Grapevines",
  "Teratoma",
  "Pliny the Elder",
  "Rosewood",
  "Caspian Sea",
  "Abandoned Altar",
  "Fatima",
  "Tigers",
  "Pistons",
  "Bison",
  "Shadow Self",
  "Astrolabe",
  "Pismire",
  "Dread",
  "Bondage",
  "Friendly Angel",
  "Minerva",
  "Hyperion",
  "Blind Faith",
  "Lost Love",
  "Vermillion",
  "The Void",
  "Demiurge",
  "Obsidian",
  "Unguent",
  "Burnt Offering"
];
